name: fuelwise
description: "Offline-first ethanol vs gasoline comparator."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.13.1

dependencies:
  flutter:
    sdk: flutter

  decimal: 3.2.6
  rational: 2.2.3
  intl: 0.20.3
  flutter_localizations:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: 6.0.0

flutter:
  uses-material-design: true
