server {
    listen 80;
    server_name _;

    return 301 https://$host:8443$request_uri;
}

server {
    listen 443 ssl;
    server_name _;

    ssl_certificate /etc/nginx/certs/server.crt;
    ssl_certificate_key /etc/nginx/certs/server.key;

    root /usr/share/nginx/html;
    index index.html;

    location = /apk/app-debug.apk {
        alias /srv/apk/app-debug.apk;
        default_type application/vnd.android.package-archive;
        add_header Content-Disposition 'attachment; filename="app-debug.apk"';
    }

    location /apk/ {
        alias /srv/apk/;
        autoindex on;
    }
}
